/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#001b3e',
        'primary-container': '#3e90ff',
        'surface-tint': '#aac7ff',
        'on-tertiary': '#472a00',
        'surface': '#10141a',
        'inverse-on-surface': '#2d3137',
        'on-background': '#dfe2eb',
        'outline': '#8b91a0',
        'on-secondary-fixed-variant': '#005236',
        'tertiary-container': '#ca8100',
        'secondary-container': '#00a572',
        'surface-container-highest': '#31353c',
        'on-tertiary-fixed': '#2a1700',
        'on-surface-variant': '#c0c6d6',
        'secondary-fixed': '#6ffbbe',
        'surface-variant': '#31353c',
        'background': '#10141a',
        'surface-container': '#1c2026',
        'outline-variant': '#414754',
        'on-tertiary-fixed-variant': '#653e00',
        'inverse-surface': '#dfe2eb',
        'on-primary-fixed-variant': '#00468d',
        'surface-container-lowest': '#0a0e14',
        'on-surface': '#dfe2eb',
        'on-error': '#690005',
        'on-secondary-fixed': '#002113',
        'primary-fixed': '#d6e3ff',
        'on-primary-container': '#002957',
        'surface-container-high': '#262a31',
        'on-secondary-container': '#00311f',
        'on-tertiary-container': '#3e2400',
        'error': '#ffb4ab',
        'inverse-primary': '#005db8',
        'secondary': '#4edea3',
        'secondary-fixed-dim': '#4edea3',
        'surface-dim': '#10141a',
        'surface-bright': '#353940',
        'primary': '#aac7ff',
        'on-error-container': '#ffdad6',
        'surface-container-low': '#181c22',
        'error-container': '#93000a',
        'tertiary-fixed-dim': '#ffb95f',
        'tertiary-fixed': '#ffddb8',
        'on-primary': '#003064',
        'on-secondary': '#003824',
        'tertiary': '#ffb95f',
        'primary-fixed-dim': '#aac7ff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        gutter: '16px',
        'container-margin': '24px',
        xl: '32px',
        md: '16px',
        lg: '24px',
        base: '4px',
        sm: '8px',
        xs: '4px',
      },
      fontFamily: {
        'headline-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'mono-data': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'mono-data': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
      },
      animation: {
        'pulse-soft': 'pulse-soft 3s infinite ease-in-out',
        'threat-ping': 'threat-ping 2s cubic-bezier(0, 0, 0.2, 1) infinite',
      },
      keyframes: {
        'pulse-soft': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
        'threat-ping': {
          '75%, 100%': { transform: 'scale(2.5)', opacity: '0' },
        },
      },
    },
  },
  plugins: [],
};
